server:
  port: 8079
eureka:
  instance:
    instance-id: ${spring.application.name}-${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    client-server:
      url: http://localhost:8090
spring:
  application:
    name: zuul-service